# For ALI!
[bar/ali]
inherit = bar/default

background = #ff6e00
background-alt = #ee5c00

foreground-alt = #fffffff
foreground = #ffffff

primary = #ffffff

afssize = #ffffff
memory = #ffffff
cpu = #ffffff
date = #ffffff
