;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/jaagr/polybar
;
;   The README contains alot of information
;
;==========================================================

; Include different bars
include-file = ~/.config/polybar/float.ini
include-file = ~/.config/polybar/bottom.ini
include-file = ~/.config/polybar/dark.ini
include-file = ~/.config/polybar/white.ini
include-file = ~/.config/polybar/basic.ini

[colors]
black = #111111
dark-gray = #444444
white = #dfdfdf
gray = #555555
yellow = #ffb52a
pink = #e60053
red = #f90000
brown = #785648
cyan = #4bffdc
blue = #0a6cf5

[bar/default]
width = 100%
height = 27
fixed-center = false
bottom = false

background = ${colors.black}
background-alt = ${colors.dark-gray}
foreground = ${colors.white}
foreground-alt = ${colors.gray}
primary = ${colors.yellow}
secondary = ${colors.pink}
alert = ${colors.red}

afssize = ${colors.brown}
memory = ${colors.cyan}
cpu = ${colors.red}
date = ${colors.blue}

line-size = 3

padding-left = 0
padding-right = 2

module-margin-left = 1
module-margin-right = 2

font-0 = fixed:pixelsize=10;1
font-1 = unifont:fontformat=truetype:size=8:antialias=false;0
font-2 = siji:pixelsize=10;1

modules-left = ${env:polybar_left}
modules-center = ${env:Polybar_center}
modules-right = ${env:polybar_right}

tray-position = right
tray-padding = 2

cursor-click = pointer
cursor-scroll = ns-resize

[bar/example]
inherit = bar/default

[module/xworkspaces]
type = internal/xworkspaces
format = <label-state>

label-active = %name%
label-active-background = ${root.background-alt}
label-active-underline= ${root.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${root.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${root.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:30:...%

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

format-prefix = " "
format-prefix-foreground = ${root.foreground-alt}
format-prefix-underline = ${root.secondary}

label-layout = %layout%
label-layout-underline = ${root.secondary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-background = ${root.secondary}
label-indicator-underline = ${root.secondary}

[module/afssize]
type = custom/script
format-prefix = "~/afs/: "
exec = bash -c 'used=$(fs quota ~/afs | cut -d'%' -f1); total=$((2*1024*1024)); echo "$used%"'
format-prefix-foreground = ${root.foreground-alt}
format-underline = ${root.afssize}
interval = 120

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "CPU:  "
format-prefix-foreground = ${root.foreground-alt}
format-underline = ${root.cpu}
label = %percentage:2%%

[module/memory]
type = internal/memory
interval = 2
format-prefix = "MEM:  "
format-prefix-foreground = ${root.foreground-alt}
format-underline = ${root.memory}
label = RAM: %percentage_used%% | SWAP: %percentage_swap_used%%

[module/date]
type = internal/date
interval = 5

date =
date-alt = " %Y-%m-%d"

time = %H:%M
time-alt = %H:%M:%S

format-prefix = 
format-prefix-foreground = ${root.foreground-alt}
format-underline = ${root.date}

label = %date% %time%

[module/powermenu]
type = custom/menu

expand-right = true

format-spacing = 1

label-open = 
label-open-foreground = ${root.secondary}
label-close =  cancel
label-close-foreground = ${root.secondary}
label-separator = |
label-separator-foreground = ${root.foreground-alt}

menu-0-0 = reboot
menu-0-0-exec = menu-open-1
menu-0-1 = power off
menu-0-1-exec = menu-open-2

menu-1-0 = cancel
menu-1-0-exec = menu-open-0
menu-1-1 = reboot
menu-1-1-exec = sudo reboot

menu-2-0 = power off
menu-2-0-exec = sudo poweroff
menu-2-1 = cancel
menu-2-1-exec = menu-open-0
