# ~/.bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

if [ -d ~/afs/bin ] ; then
	export PATH=~/afs/bin:$PATH
fi

if [ -d ~/.local/bin ] ; then
	export PATH=~/.local/bin:$PATH
fi

epiconf=~/afs/.confs/epiconf
FLAG_FILE=/tmp/tmp_flag

source $epiconf/start.sh > /dev/null
source ~/afs/.confs/config/ble/out/ble.sh

export LANG=en_US.utf8
export NNTPSERVER="news.epita.fr"

export EDITOR=vim
#export EDITOR=emacs

export BAT_THEME="Visual Studio Dark+"

# Color support for less
#export LESS_TERMCAP_mb=$'\E[01;31m'       # begin blinking
#export LESS_TERMCAP_md=$'\E[01;38;5;74m'  # begin bold
#export LESS_TERMCAP_me=$'\E[0m'           # end mode
#export LESS_TERMCAP_se=$'\E[0m'           # end standout-mode
#export LESS_TERMCAP_so=$'\E[38;5;246m'    # begin standout-mode - info box
#export LESS_TERMCAP_ue=$'\E[0m'           # end underline
#export LESS_TERMCAP_us=$'\E[04;38;5;146m' # begin underline

alias ls='ls --color=auto'
alias grep='grep --color -n'

git_branch() {
	branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
	if [ -n "$branch" ]; then
		changes=$(git status --porcelain 2>/dev/null | wc -l)
		echo -e "\e[0;31mgit:(\e[0;33m$branch\e[0;31m)±$changes"
	fi
}

for file in $(ls ~/afs/.confs/bash/*.sh); do
    source $file
done

alias i3lock='function _i3lock() {
			if [[ "$1" == "--debug" ]]; then
				i3lock
			fi
		}; _i3lock'

xfifo() {
    fifo=~/.fifo
    >$fifo
    ~/.xinitrc
    while true; do
        while IFS= read -r line; do
            $line
            > $fifo
        done < $fifo
        sleep 0.2
    done
}

xfifo &> /dev/null & disown

bind -x '"\C-l":clear'
