# ~/.bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

if [ -d ~/afs/bin ] ; then
	export PATH=~/afs/bin:$PATH
fi

if [ -d ~/.local/bin ] ; then
	export PATH=~/.local/bin:$PATH
fi

epiconf=~/afs/.confs/epiconf
FLAG_FILE=/tmp/tmp_flag

source $epiconf/start.sh > /dev/null
source ~/afs/.confs/config/ble/out/ble.sh

export LANG=en_US.utf8
export NNTPSERVER="news.epita.fr"

export EDITOR=vim
#export EDITOR=emacs

export BAT_THEME="Visual Studio Dark+"

# Color support for less
#export LESS_TERMCAP_mb=$'\E[01;31m'       # begin blinking
#export LESS_TERMCAP_md=$'\E[01;38;5;74m'  # begin bold
#export LESS_TERMCAP_me=$'\E[0m'           # end mode
#export LESS_TERMCAP_se=$'\E[0m'           # end standout-mode
#export LESS_TERMCAP_so=$'\E[38;5;246m'    # begin standout-mode - info box
#export LESS_TERMCAP_ue=$'\E[0m'           # end underline
#export LESS_TERMCAP_us=$'\E[04;38;5;146m' # begin underline

alias ls='ls --color=auto'
alias grep='grep --color -n'

git_branch() {
	branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
	if [ -n "$branch" ]; then
		changes=$(git status --porcelain 2>/dev/null | wc -l)
		echo -e "\e[0;31mgit:(\e[0;33m$branch\e[0;31m)±$changes"
	fi
}

find ~/afs/.confs/bash -name '*.sh' -exec source {} \;

alias start-serv='ip=$(ifconfig | grep "inet" | grep 255.255.255.0 | cut -d "t" -f2 | cut -d "n" -f1); echo "$ip"'

alias nix-clear='nix-collect-garbage -d'
alias bluetooth='blueman-manager &'
alias run-polybar='polybar $POLYBAR_NAME 2&> /dev/null & disown'

alias add='function _add() {
		git add "$1"
		git status
}; _add'

alias push='function _push() {
		git commit -m "$1"
		git push		
}; _push'

alias spotify='spotify 2&> /dev/null & disown'
alias deezer='deezer-enhanced 2&> /dev/null & disown'

alias i3lock='function _i3lock() {
			if [[ "$1" == "--debug" ]]; then
				i3lock
			fi
		}; _i3lock'

alias gcw="gcc -std=c99 -pedantic -Werror -Wall -Wextra -Wvla"
alias cf="clang-format -i"
alias cfe='function _cfe() {
	here=$(pwd)
	cd $(git rev-parse --show-toplevel)
	cp ~/afs/.confs/epiconf/.clang-format ./
	clang-format-epita
	rm .clang-format
	cd $here
}; _cfe'

alias rm="~/afs/.confs/epiconf/remove_to_bin.sh"
alias dbcommit="~/afs/.confs/epiconf/double_commit.sh"

alias lc='_lc() {
mkdir -p coverage
gcc -std=c99 -pedantic -Werror -Wall -Wextra -Wvla $@ -fPIC -coverage -lgcov -lcriterion
./a.out
lcov --capture --directory ./ --output-file coverage.info --ignore-errors empty --ignore-errors inconsistent
genhtml coverage.info --output-directory coverage
rm *.gcno *.gcda coverage.info a.out
firefox coverage/index.html
}; _lc'

xfifo() {
    fifo=~/.fifo
    >$fifo
    ~/.xinitrc
    while true; do
        while IFS= read -r line; do
            $line
            > $fifo
        done < $fifo
        sleep 0.2
    done
}

xfifo &> /dev/null & disown

alias movie="\i3lock; ssh -o StrictHostKeyChecking=no watch.ascii.theater && pkill i3lock"

if [ "$START_AT_AFS" = "enable" ]; then
    cd ~/afs
fi

export MANPAGER="sh -c 'awk '\''{ gsub(/\x1B\[[0-9;]*m/, \"\", \$0); gsub(/.\x08/, \"\", \$0); print }'\'' | bat --paging=always -p -lman --theme=Coldark-Dark'"
alias cat='bat --paging=never --style=plain'
alias rm='rip'
alias mr='rip -u'

bind -x '"\C-l":clear'

alias rickroll='curl -sN http://rick.jachan.dev | bash'

alias vim='nvim'
