" ~/.vimrc

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" https://github.com/tpope/vim-sensible
Plugin 'tpope/vim-sensible'
Plugin 'vim-airline/vim-airline'
Plugin 'preservim/nerdtree'
Plugin 'scrooloose/syntastic'
Plugin 'maralla/completor.vim'
Plugin 'yggdroot/indentline'
Plugin 'matze/vim-move'
" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on

runtime! plugin/sensible.vim

set encoding=utf-8 fileencodings=
syntax on

set number
set cc=80

autocmd Filetype make setlocal noexpandtab

set list listchars=tab:»·,trail:·


" per .git vim configs
" just `git config vim.settings "expandtab sw=4 sts=4"` in a git repository
" change syntax settings for this repository
let git_settings = system("git config --get vim.settings")
if strlen(git_settings)
	exe "set" git_settings
endif


" My config

:if $MOUSE == "enable"
	set mouse=a
:endif

set ts=4 sw=4

:if $INSERT_AT_START == "enable"
	start
:endif

:nnoremap <C-x> :wq<CR>
:nnoremap <C-q> :q!<CR>

:inoremap <C-x> <Esc>:wq<CR>
:inoremap <C-z> <Esc>:u<CR>i
:inoremap <C-y> <Esc>:redo<CR>i
:inoremap <C-s> <Esc>:w<CR>i
:inoremap <C-q> <Esc>:q!<CR>

:vnoremap <C-c> y
:vnoremap <C-v> p
:vnoremap <BS> d
:inoremap <C-v> <Esc>vp<Esc>i
:vnoremap cc "+y

:nnoremap < gT
:nnoremap > gt
:nnoremap + :tabe<CR>

:nnoremap <C-f> :w<Enter>:!clang-format -i % <Enter><Enter>
:inoremap <C-f> <Esc>:w<Enter>:!clang-format -i %<Enter><Enter>i

:if $CLOSE_BRACKET == "enable"
	:inoremap { {}<Left>
	:inoremap ( ()<Left>
	:inoremap [ []<Left>
	:inoremap " ""<Left>
	:inoremap ' ''<Left>
:endif

:if $SNIPPETS == "enable"
	:inoremap @for for (size_t i = 0; i < ; i++)<CR><BS>{<CR><BS>}<Left><CR><Up><Tab><Up><Up><Right><Right><Right><Right><Right><Right><Right><Right><Right><Right><Right><Right><Right><Right><Right><Right><Right><Right><Right>
	:inoremap @jfor for (size_t j = 0; j < size; j++)<CR><BS>{<CR><BS>}<Left><CR><Up><Tab>
	:inoremap @kfor for (size_t k = 0; k < size; k++)<CR><BS>{<CR><BS>}<Left><CR><Up><Tab>
	:inoremap @while while ()<CR><BS>{<CR><BS>}<Up><CR>a<BS><Up><Up><Right><Right><Right>
	:inoremap @if if ()<CR><BS>{<CR><BS>}<Up><CR>a<BS><Up><Up>
	:inoremap @elif else if ()<CR><BS>{<CR><BS>}<Up><CR>a<BS><Up><Up><Right><Right><Right><Right><Right>
	:inoremap @else else<CR><BS>{<CR><BS>}<Up><CR>a<BS>
	:inoremap @marg int main(int argc, char *argv[])<CR><BS>{<CR><BS>}<Left><CR><Up><Tab>return 0;<Up><CR>
	:inoremap @main int main(void)<CR><BS>{<CR><BS>}<Left><CR><Up><Tab>return 0;<Up><CR>
	:inoremap @std #include <stddef.h><CR>#include <stdio.h><CR>#include <stdlib.h><CR><CR>
	:inoremap @pf printf("\n");<Left><Left><Left><Left><Left>
	:inoremap @struct struct <CR>{<CR>};<Up><Up><Right><Right><Right><Right><Right>
	:inoremap @dbp #include <stdio.h><CR>int main(void)<CR><BS>{<CR>printf("%\n",);<CR>}<Up><Right><C-Right><Right><Right><Right>
    :inoremap --- ->
:endif

:inoremap <C-t> <Esc>:NERDTreeToggle<CR>i
:nnoremap <C-t> :NERDTreeToggle<CR>
":inoremap <C-F2> <Esc>:NERDTreeClose<CR>i
":nnoremap <C-F2> :NERDTreeClose<CR>i

" Highlight

:highlight Search cterm=bold ctermfg=yellow ctermbg=NONE
:highlight IncSearch cterm=underline ctermfg=yellow ctermbg=NONE
:highlight SpellBad cterm=bold ctermfg=red ctermbg=NONE
:highlight QuickFixLine cterm=NONE ctermfg=white
:highlight ColorColumn term=NONE cterm=NONE ctermbg=darkgrey ctermfg=white
:highlight CurSearch NONE
:highlight DiffChange NONE
:highlight SpellRare NONE
:highlight Pmenu cterm=NONE ctermfg=white ctermbg=236
:highlight MatchParen cterm=NONE ctermfg=lightblue ctermbg=NONE
:highlight SignColumn NONE
:highlight SyntasticErrorSign cterm=bold ctermfg=red ctermbg=black
:highlight vimError cterm=bold ctermfg=red ctermbg=black

" Plugins

"autocmd VimEnter * NERDTree
autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:aireline#extentions#syntastic#enabled=1
let g:syntastic_enable_signs = 1

let g:move_key_modifier = 'C'
let g:indentLine_char = '|'
let g:indentLine_color_term = 239
let g:indentLine_concealcursor = 'inc'
let g:indentLine_conceallevel = 1

let g:syntastic_c_config_file='~/afs/.confs/vim/.syntastic_c_config_file'

" default vimrc

" Misc
filetype indent on
syntax on

" Interface
set number
"set relativenumber
set cc=80
set showmatch
set list listchars=tab:»·,trail:·
set scrolloff=10
set wildmenu

" Indentation
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab
autocmd Filetype make setlocal noexpandtab

" Search
set ignorecase
set smartcase
set incsearch
set hlsearch
nnoremap <C-l> :noh<CR> " Hide search result with C-l

" Save
set autowrite
set autoread

" Load Vim Git settings
let git_settings = system("git config --get vim.settings")
if strlen(git_settings)
    exe "set" git_settings
endif

" Jumps back where you left the cursor when reopening a file
autocmd BufReadPost *
  \ if line("'\"") > 1 && line("'\"") <= line("$") |
  \   execute "normal! g`\"" |
  \ endif

" Better display when using termdebug
let g:termdebug_wide=1

